### ISSUE TITLE
KeyError: 'pygame_rl/data/map/soccer/soccer.tmx'

### ISSUE THREAD

**Issue by changxizhu** [ebola777/pygame-soccer#1]
Please help me!

Traceback (most recent call last):
  File "/home/cike/chauncy/coding/python/infer-policy-feature/src/train_dpiqn.py", line 284, in <module>
    NUM_ACTIONS = SoccerPlayer().get_action_space().num_actions()
  File "/home/cike/chauncy/coding/python/infer-policy-feature/src/soccer_env.py", line 210, in __init__
    self.env_options = soccer_environment.SoccerEnvironmentOptions(team_size=self.team_size, map_path=map_path, ai_frame_skip=ai_frame_skip)
  File "/home/cike/anaconda3/lib/python3.5/site-packages/pygame_rl-1.0.0-py3.5.egg/pygame_rl/scenario/soccer_environment.py", line 644, in __init__
  File "/home/cike/anaconda3/lib/python3.5/site-packages/pygame_rl-1.0.0-py3.5.egg/pygame_rl/util/file_util.py", line 23, in get_resource_path
  File "/home/cike/anaconda3/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 1203, in resource_filename
  File "/home/cike/anaconda3/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 1716, in get_resource_filename
  File "/home/cike/anaconda3/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 1737, in _extract_resource
KeyError: 'pygame_rl/data/map/soccer/soccer.tmx'

**Comment by sc420** [comment]
This is probably due to the package not being installed properly. If error still persists, please use the custom map under `sample/data/` and see the example in `sample/soccer/renderer_custom_map.py`.

**Comment by sc420** [comment]
Closing due to inactivity.
